### ISSUE TITLE
Does not work with a git-crypt key file

### ISSUE THREAD

**Issue by inspectorG4dget** [sliteteam/github-action-git-crypt-unlock#12]
Steps to reproduce:

1. Create the key file locally, using `git-crypt export-key git-crypt-key`
2. Stash this key in an S3 bucket or other remote location of choice

This works:
```
steps:
  - ...
  - name: git-crypt unlock
    run: |
      git clone https://github.com/AGWA/git-crypt.git
      cd git-crypt
      make
      sudo make install
      cd ..
      rm -rf git-crypt
      git-crypt unlock git-crypt-key
```

This does not work
```
steps:
  - name: Set git-crypt key
    id: ref
    run: echo "::set-output name=git_crypt_key::$(base64 git-crypt-key)"  # or cat git-crypt-key | base64
  - name: decrypt
    uses: sliteteam/github-action-git-crypt-unlock@1.2.0
    env:
      GIT_CRYPT_KEY: ${{ steps.ref.outputs.git_crypt_key }}
```
